//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBHTenancyAPITest.ArrearsAgreementService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IArrearsAgreementService", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserFieldEntity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebRequest))]
    public partial class ArrearsAgreementService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateArrearsAgreementOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddPaymentScheduleOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateArrearsActionOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletePaymentScheduleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateArrearsAgreementOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTenancyAgreementOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetArrearsAgreementByRefOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetArrearsAgreementListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetArrearsActionHistoryOperationCompleted;
        
        /// CodeRemarks
        public ArrearsAgreementService() {
            this.Url = "http://lbhuhwwebp01/civica-uh-gateway-dev/webservices/ArrearsAgreementService.svc" +
                "";
        }
        
        public ArrearsAgreementService(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        public event CreateArrearsAgreementCompletedEventHandler CreateArrearsAgreementCompleted;
        
        /// CodeRemarks
        public event AddPaymentScheduleCompletedEventHandler AddPaymentScheduleCompleted;
        
        /// CodeRemarks
        public event CreateArrearsActionCompletedEventHandler CreateArrearsActionCompleted;
        
        /// CodeRemarks
        public event DeletePaymentScheduleCompletedEventHandler DeletePaymentScheduleCompleted;
        
        /// CodeRemarks
        public event UpdateArrearsAgreementCompletedEventHandler UpdateArrearsAgreementCompleted;
        
        /// CodeRemarks
        public event UpdateTenancyAgreementCompletedEventHandler UpdateTenancyAgreementCompleted;
        
        /// CodeRemarks
        public event GetArrearsAgreementByRefCompletedEventHandler GetArrearsAgreementByRefCompleted;
        
        /// CodeRemarks
        public event GetArrearsAgreementListCompletedEventHandler GetArrearsAgreementListCompleted;
        
        /// CodeRemarks
        public event GetArrearsActionHistoryCompletedEventHandler GetArrearsActionHistoryCompleted;
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/CreateArrearsA" +
            "greement", RequestNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", ResponseNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArrearsAgreementResponse CreateArrearsAgreement([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ArrearsAgreementRequest dto) {
            object[] results = this.Invoke("CreateArrearsAgreement", new object[] {
                        dto});
            return ((ArrearsAgreementResponse)(results[0]));
        }
        
        /// CodeRemarks
        public void CreateArrearsAgreementAsync(ArrearsAgreementRequest dto) {
            this.CreateArrearsAgreementAsync(dto, null);
        }
        
        /// CodeRemarks
        public void CreateArrearsAgreementAsync(ArrearsAgreementRequest dto, object userState) {
            if ((this.CreateArrearsAgreementOperationCompleted == null)) {
                this.CreateArrearsAgreementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateArrearsAgreementOperationCompleted);
            }
            this.InvokeAsync("CreateArrearsAgreement", new object[] {
                        dto}, this.CreateArrearsAgreementOperationCompleted, userState);
        }
        
        private void OnCreateArrearsAgreementOperationCompleted(object arg) {
            if ((this.CreateArrearsAgreementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateArrearsAgreementCompleted(this, new CreateArrearsAgreementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/AddPaymentSche" +
            "dule", RequestNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", ResponseNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArrearsAgreementResponse AddPaymentSchedule([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] PaymentScheduleRequest dto) {
            object[] results = this.Invoke("AddPaymentSchedule", new object[] {
                        dto});
            return ((ArrearsAgreementResponse)(results[0]));
        }
        
        /// CodeRemarks
        public void AddPaymentScheduleAsync(PaymentScheduleRequest dto) {
            this.AddPaymentScheduleAsync(dto, null);
        }
        
        /// CodeRemarks
        public void AddPaymentScheduleAsync(PaymentScheduleRequest dto, object userState) {
            if ((this.AddPaymentScheduleOperationCompleted == null)) {
                this.AddPaymentScheduleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddPaymentScheduleOperationCompleted);
            }
            this.InvokeAsync("AddPaymentSchedule", new object[] {
                        dto}, this.AddPaymentScheduleOperationCompleted, userState);
        }
        
        private void OnAddPaymentScheduleOperationCompleted(object arg) {
            if ((this.AddPaymentScheduleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddPaymentScheduleCompleted(this, new AddPaymentScheduleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/CreateArrearsA" +
            "ction", RequestNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", ResponseNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArrearsActionResponse CreateArrearsAction([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ArrearsActionCreateRequest dto) {
            object[] results = this.Invoke("CreateArrearsAction", new object[] {
                        dto});
            return ((ArrearsActionResponse)(results[0]));
        }
        
        /// CodeRemarks
        public void CreateArrearsActionAsync(ArrearsActionCreateRequest dto) {
            this.CreateArrearsActionAsync(dto, null);
        }
        
        /// CodeRemarks
        public void CreateArrearsActionAsync(ArrearsActionCreateRequest dto, object userState) {
            if ((this.CreateArrearsActionOperationCompleted == null)) {
                this.CreateArrearsActionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateArrearsActionOperationCompleted);
            }
            this.InvokeAsync("CreateArrearsAction", new object[] {
                        dto}, this.CreateArrearsActionOperationCompleted, userState);
        }
        
        private void OnCreateArrearsActionOperationCompleted(object arg) {
            if ((this.CreateArrearsActionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateArrearsActionCompleted(this, new CreateArrearsActionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/DeletePaymentS" +
            "chedule", RequestNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", ResponseNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArrearsAgreementResponse DeletePaymentSchedule([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] DeletePaymentScheduleRequest dto) {
            object[] results = this.Invoke("DeletePaymentSchedule", new object[] {
                        dto});
            return ((ArrearsAgreementResponse)(results[0]));
        }
        
        /// CodeRemarks
        public void DeletePaymentScheduleAsync(DeletePaymentScheduleRequest dto) {
            this.DeletePaymentScheduleAsync(dto, null);
        }
        
        /// CodeRemarks
        public void DeletePaymentScheduleAsync(DeletePaymentScheduleRequest dto, object userState) {
            if ((this.DeletePaymentScheduleOperationCompleted == null)) {
                this.DeletePaymentScheduleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePaymentScheduleOperationCompleted);
            }
            this.InvokeAsync("DeletePaymentSchedule", new object[] {
                        dto}, this.DeletePaymentScheduleOperationCompleted, userState);
        }
        
        private void OnDeletePaymentScheduleOperationCompleted(object arg) {
            if ((this.DeletePaymentScheduleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletePaymentScheduleCompleted(this, new DeletePaymentScheduleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/UpdateArrearsA" +
            "greement", RequestNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", ResponseNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArrearsAgreementResponse UpdateArrearsAgreement([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ArrearsAgreementRequest dto) {
            object[] results = this.Invoke("UpdateArrearsAgreement", new object[] {
                        dto});
            return ((ArrearsAgreementResponse)(results[0]));
        }
        
        /// CodeRemarks
        public void UpdateArrearsAgreementAsync(ArrearsAgreementRequest dto) {
            this.UpdateArrearsAgreementAsync(dto, null);
        }
        
        /// CodeRemarks
        public void UpdateArrearsAgreementAsync(ArrearsAgreementRequest dto, object userState) {
            if ((this.UpdateArrearsAgreementOperationCompleted == null)) {
                this.UpdateArrearsAgreementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateArrearsAgreementOperationCompleted);
            }
            this.InvokeAsync("UpdateArrearsAgreement", new object[] {
                        dto}, this.UpdateArrearsAgreementOperationCompleted, userState);
        }
        
        private void OnUpdateArrearsAgreementOperationCompleted(object arg) {
            if ((this.UpdateArrearsAgreementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateArrearsAgreementCompleted(this, new UpdateArrearsAgreementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/UpdateTenancyA" +
            "greement", RequestNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", ResponseNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WebResponse UpdateTenancyAgreement([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TenancyArrearsUpdateRequest dto) {
            object[] results = this.Invoke("UpdateTenancyAgreement", new object[] {
                        dto});
            return ((WebResponse)(results[0]));
        }
        
        /// CodeRemarks
        public void UpdateTenancyAgreementAsync(TenancyArrearsUpdateRequest dto) {
            this.UpdateTenancyAgreementAsync(dto, null);
        }
        
        /// CodeRemarks
        public void UpdateTenancyAgreementAsync(TenancyArrearsUpdateRequest dto, object userState) {
            if ((this.UpdateTenancyAgreementOperationCompleted == null)) {
                this.UpdateTenancyAgreementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTenancyAgreementOperationCompleted);
            }
            this.InvokeAsync("UpdateTenancyAgreement", new object[] {
                        dto}, this.UpdateTenancyAgreementOperationCompleted, userState);
        }
        
        private void OnUpdateTenancyAgreementOperationCompleted(object arg) {
            if ((this.UpdateTenancyAgreementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTenancyAgreementCompleted(this, new UpdateTenancyAgreementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/GetArrearsAgre" +
            "ementByRef", RequestNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", ResponseNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArrearsAgreementResponse GetArrearsAgreementByRef([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ByReferenceRequest dto) {
            object[] results = this.Invoke("GetArrearsAgreementByRef", new object[] {
                        dto});
            return ((ArrearsAgreementResponse)(results[0]));
        }
        
        /// CodeRemarks
        public void GetArrearsAgreementByRefAsync(ByReferenceRequest dto) {
            this.GetArrearsAgreementByRefAsync(dto, null);
        }
        
        /// CodeRemarks
        public void GetArrearsAgreementByRefAsync(ByReferenceRequest dto, object userState) {
            if ((this.GetArrearsAgreementByRefOperationCompleted == null)) {
                this.GetArrearsAgreementByRefOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetArrearsAgreementByRefOperationCompleted);
            }
            this.InvokeAsync("GetArrearsAgreementByRef", new object[] {
                        dto}, this.GetArrearsAgreementByRefOperationCompleted, userState);
        }
        
        private void OnGetArrearsAgreementByRefOperationCompleted(object arg) {
            if ((this.GetArrearsAgreementByRefCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetArrearsAgreementByRefCompleted(this, new GetArrearsAgreementByRefCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/GetArrearsAgre" +
            "ementList", RequestNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", ResponseNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArrearsAgreementListResponse GetArrearsAgreementList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ArrearsAgreementSearchRequest dto) {
            object[] results = this.Invoke("GetArrearsAgreementList", new object[] {
                        dto});
            return ((ArrearsAgreementListResponse)(results[0]));
        }
        
        /// CodeRemarks
        public void GetArrearsAgreementListAsync(ArrearsAgreementSearchRequest dto) {
            this.GetArrearsAgreementListAsync(dto, null);
        }
        
        /// CodeRemarks
        public void GetArrearsAgreementListAsync(ArrearsAgreementSearchRequest dto, object userState) {
            if ((this.GetArrearsAgreementListOperationCompleted == null)) {
                this.GetArrearsAgreementListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetArrearsAgreementListOperationCompleted);
            }
            this.InvokeAsync("GetArrearsAgreementList", new object[] {
                        dto}, this.GetArrearsAgreementListOperationCompleted, userState);
        }
        
        private void OnGetArrearsAgreementListOperationCompleted(object arg) {
            if ((this.GetArrearsAgreementListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetArrearsAgreementListCompleted(this, new GetArrearsAgreementListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/GetArrearsActi" +
            "onHistory", RequestNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", ResponseNamespace="http://schemas.civica.co.uk/UHWeb/2013/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArrearsActionHistoryResponse GetArrearsActionHistory([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ArrearsActionSearchRequest dto) {
            object[] results = this.Invoke("GetArrearsActionHistory", new object[] {
                        dto});
            return ((ArrearsActionHistoryResponse)(results[0]));
        }
        
        /// CodeRemarks
        public void GetArrearsActionHistoryAsync(ArrearsActionSearchRequest dto) {
            this.GetArrearsActionHistoryAsync(dto, null);
        }
        
        /// CodeRemarks
        public void GetArrearsActionHistoryAsync(ArrearsActionSearchRequest dto, object userState) {
            if ((this.GetArrearsActionHistoryOperationCompleted == null)) {
                this.GetArrearsActionHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetArrearsActionHistoryOperationCompleted);
            }
            this.InvokeAsync("GetArrearsActionHistory", new object[] {
                        dto}, this.GetArrearsActionHistoryOperationCompleted, userState);
        }
        
        private void OnGetArrearsActionHistoryOperationCompleted(object arg) {
            if ((this.GetArrearsActionHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetArrearsActionHistoryCompleted(this, new GetArrearsActionHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsAgreementRequest : WebRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArrearsAgreementInfo Agreement;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ArrearsScheduledPaymentInfo[] PaymentSchedule;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrearsAgreementDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsAgreementInfo : UserFieldEntity {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ArrearsAgreementStatusCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Comment;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FcaDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FcaDateSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FirstCheck;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstCheckSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstCheckFrequencyTypeCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsBreached;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsBreachedSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MonitorBalanceCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NextCheck;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NextCheckSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NextCheckFrequencyTypeCode;
        
        /// <remarks/>
        public int NoPrePay;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoPrePaySpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reference;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> StartBalance;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartBalanceSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StartDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TenancyAgreementRef;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Tolerance;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToleranceSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TenancyArrearsInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrearsScheduledPaymentInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrearsScheduledPaymentDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrearsAgreementInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrearsAgreementDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class UserFieldEntity {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public UserField[] UserFieldList;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class UserField {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Key;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsActionHistoryDto {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ArrearsActionLogDto[] ArrearsActions;
        
        /// <remarks/>
        public decimal CurrentBalance;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrentBalanceSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HouseholdRef;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PropertyRef;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SuggestedAction;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SuggestedActionDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuggestedActionDateSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TenancyAgreementRef;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TenancyTitle;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsActionLogDto {
        
        /// <remarks/>
        public decimal ActionBalance;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionBalanceSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActionCategory;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActionCode;
        
        /// <remarks/>
        public System.DateTime ActionDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionDateSpecified;
        
        /// <remarks/>
        public int ActionNo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionNoSpecified;
        
        /// <remarks/>
        public int ActionSet;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSetSpecified;
        
        /// <remarks/>
        public bool Confirmation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConfirmationSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeferredTo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeferredToSpecified;
        
        /// <remarks/>
        public int Id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified;
        
        /// <remarks/>
        public bool IsCommentOnly;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsCommentOnlySpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TenancyAgreementRef;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrearsActionHistoryResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrearsAgreementListResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrearsActionResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrearsAgreementResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class WebResponse {
        
        /// <remarks/>
        public int ErrorCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorCodeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorMessage;
        
        /// <remarks/>
        public bool Success;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsActionHistoryResponse : WebResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArrearsActionHistoryDto ArrearsHistory;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsAgreementListResponse : WebResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ArrearsAgreementDto[] AgreementList;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsAgreementDto : ArrearsAgreementInfo {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ArrearsScheduledPaymentDto[] PaymentSchedule;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsScheduledPaymentDto : ArrearsScheduledPaymentInfo {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrearsScheduledPaymentDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsScheduledPaymentInfo : UserFieldEntity {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Amount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ArrearsFrequencyCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Comments;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EndDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndDateSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StartDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsActionResponse : WebResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArrearsActionLogDto ArrearsAction;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsAgreementResponse : WebResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArrearsAgreementDto Agreement;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsActionSearch {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ActionBalance;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionBalanceSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActionCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ActionDateFrom;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionDateFromSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ActionDateTo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionDateToSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ActionSet;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSetSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Comment;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> CommentOnly;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommentOnlySpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> LatestActionSetOnly;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatestActionSetOnlySpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MaxRecords;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxRecordsSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SkipRecords;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SkipRecordsSpecified;
        
        /// <remarks/>
        public bool SortAscending;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SortAscendingSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TenancyAgreementRef;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsAgreementSearch {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HouseholdRef;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MaxRecords;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxRecordsSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PropertyRef;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ShortAddress;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TenancyAgreementRef;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TenancyStartDateFrom;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TenancyStartDateFromSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TenancyStartDateTo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TenancyStartDateToSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TenancyTitle;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsActionInfo {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ActionBalance;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionBalanceSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActionCategory;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActionCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Comment;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Confirmation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConfirmationSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeferredTo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeferredToSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsCommentOnly;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsCommentOnlySpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> NewSetRequired;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NewSetRequiredSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TenancyAgreementRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class UserCredential {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserPassword;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrearsActionSearchRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrearsAgreementSearchRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ByReferenceRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TenancyArrearsUpdateRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeletePaymentScheduleRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrearsActionCreateRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentScheduleRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrearsAgreementRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class WebRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CompanyCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserCredential DirectUser;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MasterPassword;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SessionToken;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SourceSystem;
        
        /// <remarks/>
        public int UserId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserIdSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsActionSearchRequest : WebRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArrearsActionSearch ActionSearch;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsAgreementSearchRequest : WebRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArrearsAgreementSearch AgreementSearch;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ByReferenceRequest : WebRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reference;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class TenancyArrearsUpdateRequest : WebRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TenancyArrearsInfo ArrearsInfo;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class TenancyArrearsInfo : UserFieldEntity {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> CommitteeApproved;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommitteeApprovedSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CourtDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CourtDateSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> CourtSummonsIssued;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CourtSummonsIssuedSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EvictionDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EvictionDateSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> EvictionGranted;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EvictionGrantedSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NOSPExpiryDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NOSPExpiryDateSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> NOSPIssued;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NOSPIssuedSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NTQExpiryDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NTQExpiryDateSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> NTQIssued;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NTQIssuedSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> POIssued;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool POIssuedSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> SuspendedPOIssued;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuspendedPOIssuedSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TenancyAgreementRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class DeletePaymentScheduleRequest : WebRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ArrearsAgreementRef;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public int[] PaymentScheduleIds;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsActionCreateRequest : WebRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArrearsActionInfo ArrearsAction;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class PaymentScheduleRequest : WebRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ArrearsAgreementRef;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ArrearsScheduledPaymentInfo[] PaymentSchedule;
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    public delegate void CreateArrearsAgreementCompletedEventHandler(object sender, CreateArrearsAgreementCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateArrearsAgreementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateArrearsAgreementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public ArrearsAgreementResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArrearsAgreementResponse)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    public delegate void AddPaymentScheduleCompletedEventHandler(object sender, AddPaymentScheduleCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddPaymentScheduleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddPaymentScheduleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public ArrearsAgreementResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArrearsAgreementResponse)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    public delegate void CreateArrearsActionCompletedEventHandler(object sender, CreateArrearsActionCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateArrearsActionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateArrearsActionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public ArrearsActionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArrearsActionResponse)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    public delegate void DeletePaymentScheduleCompletedEventHandler(object sender, DeletePaymentScheduleCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeletePaymentScheduleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeletePaymentScheduleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public ArrearsAgreementResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArrearsAgreementResponse)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    public delegate void UpdateArrearsAgreementCompletedEventHandler(object sender, UpdateArrearsAgreementCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateArrearsAgreementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateArrearsAgreementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public ArrearsAgreementResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArrearsAgreementResponse)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    public delegate void UpdateTenancyAgreementCompletedEventHandler(object sender, UpdateTenancyAgreementCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTenancyAgreementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTenancyAgreementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public WebResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebResponse)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    public delegate void GetArrearsAgreementByRefCompletedEventHandler(object sender, GetArrearsAgreementByRefCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetArrearsAgreementByRefCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetArrearsAgreementByRefCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public ArrearsAgreementResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArrearsAgreementResponse)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    public delegate void GetArrearsAgreementListCompletedEventHandler(object sender, GetArrearsAgreementListCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetArrearsAgreementListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetArrearsAgreementListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public ArrearsAgreementListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArrearsAgreementListResponse)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    public delegate void GetArrearsActionHistoryCompletedEventHandler(object sender, GetArrearsActionHistoryCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.5.3.7")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetArrearsActionHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetArrearsActionHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public ArrearsActionHistoryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArrearsActionHistoryResponse)(this.results[0]));
            }
        }
    }
}
